### ISSUE TITLE
Database Initialization - SQL

### ISSUE THREAD

**Issue by rlodhicode** [CSCI3308-Group7-Book-Tracker/book-tracker#8]
>As a user, we will need to be able to store and access retrievable metadata information. This can involve, review information, book information, user information and more.

**Acceptance Criteria**
I know this story is complete when 

- a DDL file is created and stored in an init_*.sql file. 
- The DDL components should map between tables, correctly defining keys and any foreign key relationships.
- Tables should be normalized and defined to account for any tentative features (user book reviews, user information [including login info], book information, etc.)

**Comment by LucasFiedler** [comment]
Users table, books table, users to reviews, reviews to book, reviews, users to books
